import { VoucherActionType } from 'shared/ActionType'

export const UPLOAD_SUBMISSION_ATTACHMENT_FILE = new VoucherActionType('UPLOAD_SUBMISSION_ATTACHMENT_FILE')
export const MASS_UPLOAD_SUBMISSION_ATTACHMENT_FILE = new VoucherActionType('MASS_UPLOAD_SUBMISSION_ATTACHMENT_FILE')
export const DOWNLOAD_SUBMISSION_ATTACHMENT_FILE = new VoucherActionType('DOWNLOAD_SUBMISSION_ATTACHMENT_FILE')
